/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DeployJudge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DeployJudge__factory>;
    getContractFactory(
      name: "ICOR",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICOR__factory>;
    getContractFactory(
      name: "Justice",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Justice__factory>;
    getContractFactory(
      name: "MockCORToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCORToken__factory>;
    getContractFactory(
      name: "ReputationRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationRegistry__factory>;

    getContractAt(
      name: "DeployJudge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DeployJudge>;
    getContractAt(
      name: "ICOR",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICOR>;
    getContractAt(
      name: "Justice",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Justice>;
    getContractAt(
      name: "MockCORToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCORToken>;
    getContractAt(
      name: "ReputationRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationRegistry>;

    deployContract(
      name: "DeployJudge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DeployJudge>;
    deployContract(
      name: "ICOR",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICOR>;
    deployContract(
      name: "Justice",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Justice>;
    deployContract(
      name: "MockCORToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCORToken>;
    deployContract(
      name: "ReputationRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationRegistry>;

    deployContract(
      name: "DeployJudge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DeployJudge>;
    deployContract(
      name: "ICOR",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICOR>;
    deployContract(
      name: "Justice",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Justice>;
    deployContract(
      name: "MockCORToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCORToken>;
    deployContract(
      name: "ReputationRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
