/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Justice {
  export type EvidenceBundleStruct = {
    promptHash: string;
    minerResult: string;
    logicTrace: string;
    poiHash: string;
    ipfsHash: string;
    modelId: BigNumberish;
    miner: AddressLike;
    timestamp: BigNumberish;
  };

  export type EvidenceBundleStructOutput = [
    promptHash: string,
    minerResult: string,
    logicTrace: string,
    poiHash: string,
    ipfsHash: string,
    modelId: bigint,
    miner: string,
    timestamp: bigint
  ] & {
    promptHash: string;
    minerResult: string;
    logicTrace: string;
    poiHash: string;
    ipfsHash: string;
    modelId: bigint;
    miner: string;
    timestamp: bigint;
  };

  export type DisputeStruct = {
    id: BigNumberish;
    evidence: Justice.EvidenceBundleStruct;
    challenger: AddressLike;
    challengeBond: BigNumberish;
    status: BigNumberish;
    verdict: BigNumberish;
    judge: AddressLike;
    verdictReasoning: string;
    startTime: BigNumberish;
    settlementTime: BigNumberish;
    slashAmount: BigNumberish;
    rewardAmount: BigNumberish;
  };

  export type DisputeStructOutput = [
    id: bigint,
    evidence: Justice.EvidenceBundleStructOutput,
    challenger: string,
    challengeBond: bigint,
    status: bigint,
    verdict: bigint,
    judge: string,
    verdictReasoning: string,
    startTime: bigint,
    settlementTime: bigint,
    slashAmount: bigint,
    rewardAmount: bigint
  ] & {
    id: bigint;
    evidence: Justice.EvidenceBundleStructOutput;
    challenger: string;
    challengeBond: bigint;
    status: bigint;
    verdict: bigint;
    judge: string;
    verdictReasoning: string;
    startTime: bigint;
    settlementTime: bigint;
    slashAmount: bigint;
    rewardAmount: bigint;
  };
}

export interface JusticeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accumulatedFees"
      | "calculateOutcomes"
      | "challengeWindowDuration"
      | "challengerDisputes"
      | "challengerRewardPercentage"
      | "corToken"
      | "disputeCounter"
      | "disputes"
      | "getChallengerDisputes"
      | "getDispute"
      | "getMinerDisputes"
      | "getMinerTrustScore"
      | "hasAgentIdentity"
      | "initiateChallenge"
      | "isAgentIdentity"
      | "isValidator"
      | "maxBond"
      | "minBond"
      | "minerDisputes"
      | "minerTrustScore"
      | "owner"
      | "platformFeePercentage"
      | "registerAgentIdentity"
      | "registerValidator"
      | "reputationRegistry"
      | "revokeValidator"
      | "setBondLimits"
      | "setChallengeWindowDuration"
      | "setReputationRegistry"
      | "setSlashParameters"
      | "settleDispute"
      | "slashPercentage"
      | "submitVerdict"
      | "validatorRegistry"
      | "validatorReputation"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentIdentityRegistered"
      | "BondRefunded"
      | "ChallengeWindowed"
      | "DisputeInitiated"
      | "DisputeSettled"
      | "FeeWithdrawn"
      | "MinerSlashed"
      | "ValidatorRegistered"
      | "VerdictSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateOutcomes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeWindowDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengerDisputes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengerRewardPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "corToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disputeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallengerDisputes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinerDisputes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinerTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAgentIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateChallenge",
    values: [Justice.EvidenceBundleStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxBond", values?: undefined): string;
  encodeFunctionData(functionFragment: "minBond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minerDisputes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minerTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgentIdentity",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerValidator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChallengeWindowDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlashParameters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerdict",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateOutcomes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeWindowDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengerDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengerRewardPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "corToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChallengerDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinerDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinerTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAgentIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxBond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minerDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minerTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgentIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChallengeWindowDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlashParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace AgentIdentityRegisteredEvent {
  export type InputTuple = [agent: AddressLike, agentType: string];
  export type OutputTuple = [agent: string, agentType: string];
  export interface OutputObject {
    agent: string;
    agentType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondRefundedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    challenger: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    challenger: string,
    amount: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    challenger: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeWindowedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    windowEndTime: BigNumberish
  ];
  export type OutputTuple = [disputeId: bigint, windowEndTime: bigint];
  export interface OutputObject {
    disputeId: bigint;
    windowEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeInitiatedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    challenger: AddressLike,
    miner: AddressLike,
    bond: BigNumberish,
    ipfsHash: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    challenger: string,
    miner: string,
    bond: bigint,
    ipfsHash: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    challenger: string;
    miner: string;
    bond: bigint;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeSettledEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    miner: AddressLike,
    challenger: AddressLike,
    slashAmount: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    miner: string,
    challenger: string,
    slashAmount: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    miner: string;
    challenger: string;
    slashAmount: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerSlashedEvent {
  export type InputTuple = [
    miner: AddressLike,
    amount: BigNumberish,
    newTrustScore: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    amount: bigint,
    newTrustScore: bigint
  ];
  export interface OutputObject {
    miner: string;
    amount: bigint;
    newTrustScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegisteredEvent {
  export type InputTuple = [
    validator: AddressLike,
    initialReputation: BigNumberish
  ];
  export type OutputTuple = [validator: string, initialReputation: bigint];
  export interface OutputObject {
    validator: string;
    initialReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictSubmittedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    judge: AddressLike,
    verdict: BigNumberish,
    slashAmount: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    judge: string,
    verdict: bigint,
    slashAmount: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    judge: string;
    verdict: bigint;
    slashAmount: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Justice extends BaseContract {
  connect(runner?: ContractRunner | null): Justice;
  waitForDeployment(): Promise<this>;

  interface: JusticeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  calculateOutcomes: TypedContractMethod<
    [_disputeId: BigNumberish],
    [[bigint, bigint] & { slashAmount: bigint; rewardAmount: bigint }],
    "view"
  >;

  challengeWindowDuration: TypedContractMethod<[], [bigint], "view">;

  challengerDisputes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  challengerRewardPercentage: TypedContractMethod<[], [bigint], "view">;

  corToken: TypedContractMethod<[], [string], "view">;

  disputeCounter: TypedContractMethod<[], [bigint], "view">;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        Justice.EvidenceBundleStructOutput,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        evidence: Justice.EvidenceBundleStructOutput;
        challenger: string;
        challengeBond: bigint;
        status: bigint;
        verdict: bigint;
        judge: string;
        verdictReasoning: string;
        startTime: bigint;
        settlementTime: bigint;
        slashAmount: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;

  getChallengerDisputes: TypedContractMethod<
    [_challenger: AddressLike],
    [bigint[]],
    "view"
  >;

  getDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [Justice.DisputeStructOutput],
    "view"
  >;

  getMinerDisputes: TypedContractMethod<
    [_miner: AddressLike],
    [bigint[]],
    "view"
  >;

  getMinerTrustScore: TypedContractMethod<
    [_miner: AddressLike],
    [bigint],
    "view"
  >;

  hasAgentIdentity: TypedContractMethod<
    [_agent: AddressLike],
    [boolean],
    "view"
  >;

  initiateChallenge: TypedContractMethod<
    [_evidence: Justice.EvidenceBundleStruct, _bond: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  isAgentIdentity: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isValidator: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  maxBond: TypedContractMethod<[], [bigint], "view">;

  minBond: TypedContractMethod<[], [bigint], "view">;

  minerDisputes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  minerTrustScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  registerAgentIdentity: TypedContractMethod<
    [_agentType: string],
    [void],
    "nonpayable"
  >;

  registerValidator: TypedContractMethod<
    [_validator: AddressLike, _initialReputation: BigNumberish],
    [void],
    "nonpayable"
  >;

  reputationRegistry: TypedContractMethod<[], [string], "view">;

  revokeValidator: TypedContractMethod<
    [_validator: AddressLike],
    [void],
    "nonpayable"
  >;

  setBondLimits: TypedContractMethod<
    [_minBond: BigNumberish, _maxBond: BigNumberish],
    [void],
    "nonpayable"
  >;

  setChallengeWindowDuration: TypedContractMethod<
    [_duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReputationRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setSlashParameters: TypedContractMethod<
    [_slashPercentage: BigNumberish, _challengerRewardPercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  slashPercentage: TypedContractMethod<[], [bigint], "view">;

  submitVerdict: TypedContractMethod<
    [
      _disputeId: BigNumberish,
      _verdict: BigNumberish,
      _verdictReasoning: string
    ],
    [void],
    "nonpayable"
  >;

  validatorRegistry: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  validatorReputation: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateOutcomes"
  ): TypedContractMethod<
    [_disputeId: BigNumberish],
    [[bigint, bigint] & { slashAmount: bigint; rewardAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "challengeWindowDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengerDisputes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "challengerRewardPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "corToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        Justice.EvidenceBundleStructOutput,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        evidence: Justice.EvidenceBundleStructOutput;
        challenger: string;
        challengeBond: bigint;
        status: bigint;
        verdict: bigint;
        judge: string;
        verdictReasoning: string;
        startTime: bigint;
        settlementTime: bigint;
        slashAmount: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChallengerDisputes"
  ): TypedContractMethod<[_challenger: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [_disputeId: BigNumberish],
    [Justice.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinerDisputes"
  ): TypedContractMethod<[_miner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMinerTrustScore"
  ): TypedContractMethod<[_miner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasAgentIdentity"
  ): TypedContractMethod<[_agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initiateChallenge"
  ): TypedContractMethod<
    [_evidence: Justice.EvidenceBundleStruct, _bond: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAgentIdentity"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidator"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minerDisputes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "minerTrustScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgentIdentity"
  ): TypedContractMethod<[_agentType: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerValidator"
  ): TypedContractMethod<
    [_validator: AddressLike, _initialReputation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeValidator"
  ): TypedContractMethod<[_validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBondLimits"
  ): TypedContractMethod<
    [_minBond: BigNumberish, _maxBond: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setChallengeWindowDuration"
  ): TypedContractMethod<[_duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReputationRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlashParameters"
  ): TypedContractMethod<
    [_slashPercentage: BigNumberish, _challengerRewardPercentage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitVerdict"
  ): TypedContractMethod<
    [
      _disputeId: BigNumberish,
      _verdict: BigNumberish,
      _verdictReasoning: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorRegistry"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "validatorReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentIdentityRegistered"
  ): TypedContractEvent<
    AgentIdentityRegisteredEvent.InputTuple,
    AgentIdentityRegisteredEvent.OutputTuple,
    AgentIdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BondRefunded"
  ): TypedContractEvent<
    BondRefundedEvent.InputTuple,
    BondRefundedEvent.OutputTuple,
    BondRefundedEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeWindowed"
  ): TypedContractEvent<
    ChallengeWindowedEvent.InputTuple,
    ChallengeWindowedEvent.OutputTuple,
    ChallengeWindowedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeInitiated"
  ): TypedContractEvent<
    DisputeInitiatedEvent.InputTuple,
    DisputeInitiatedEvent.OutputTuple,
    DisputeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeSettled"
  ): TypedContractEvent<
    DisputeSettledEvent.InputTuple,
    DisputeSettledEvent.OutputTuple,
    DisputeSettledEvent.OutputObject
  >;
  getEvent(
    key: "FeeWithdrawn"
  ): TypedContractEvent<
    FeeWithdrawnEvent.InputTuple,
    FeeWithdrawnEvent.OutputTuple,
    FeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MinerSlashed"
  ): TypedContractEvent<
    MinerSlashedEvent.InputTuple,
    MinerSlashedEvent.OutputTuple,
    MinerSlashedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistered"
  ): TypedContractEvent<
    ValidatorRegisteredEvent.InputTuple,
    ValidatorRegisteredEvent.OutputTuple,
    ValidatorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VerdictSubmitted"
  ): TypedContractEvent<
    VerdictSubmittedEvent.InputTuple,
    VerdictSubmittedEvent.OutputTuple,
    VerdictSubmittedEvent.OutputObject
  >;

  filters: {
    "AgentIdentityRegistered(address,string)": TypedContractEvent<
      AgentIdentityRegisteredEvent.InputTuple,
      AgentIdentityRegisteredEvent.OutputTuple,
      AgentIdentityRegisteredEvent.OutputObject
    >;
    AgentIdentityRegistered: TypedContractEvent<
      AgentIdentityRegisteredEvent.InputTuple,
      AgentIdentityRegisteredEvent.OutputTuple,
      AgentIdentityRegisteredEvent.OutputObject
    >;

    "BondRefunded(uint256,address,uint256)": TypedContractEvent<
      BondRefundedEvent.InputTuple,
      BondRefundedEvent.OutputTuple,
      BondRefundedEvent.OutputObject
    >;
    BondRefunded: TypedContractEvent<
      BondRefundedEvent.InputTuple,
      BondRefundedEvent.OutputTuple,
      BondRefundedEvent.OutputObject
    >;

    "ChallengeWindowed(uint256,uint256)": TypedContractEvent<
      ChallengeWindowedEvent.InputTuple,
      ChallengeWindowedEvent.OutputTuple,
      ChallengeWindowedEvent.OutputObject
    >;
    ChallengeWindowed: TypedContractEvent<
      ChallengeWindowedEvent.InputTuple,
      ChallengeWindowedEvent.OutputTuple,
      ChallengeWindowedEvent.OutputObject
    >;

    "DisputeInitiated(uint256,address,address,uint256,string)": TypedContractEvent<
      DisputeInitiatedEvent.InputTuple,
      DisputeInitiatedEvent.OutputTuple,
      DisputeInitiatedEvent.OutputObject
    >;
    DisputeInitiated: TypedContractEvent<
      DisputeInitiatedEvent.InputTuple,
      DisputeInitiatedEvent.OutputTuple,
      DisputeInitiatedEvent.OutputObject
    >;

    "DisputeSettled(uint256,address,address,uint256,uint256)": TypedContractEvent<
      DisputeSettledEvent.InputTuple,
      DisputeSettledEvent.OutputTuple,
      DisputeSettledEvent.OutputObject
    >;
    DisputeSettled: TypedContractEvent<
      DisputeSettledEvent.InputTuple,
      DisputeSettledEvent.OutputTuple,
      DisputeSettledEvent.OutputObject
    >;

    "FeeWithdrawn(address,uint256)": TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;
    FeeWithdrawn: TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;

    "MinerSlashed(address,uint256,uint256)": TypedContractEvent<
      MinerSlashedEvent.InputTuple,
      MinerSlashedEvent.OutputTuple,
      MinerSlashedEvent.OutputObject
    >;
    MinerSlashed: TypedContractEvent<
      MinerSlashedEvent.InputTuple,
      MinerSlashedEvent.OutputTuple,
      MinerSlashedEvent.OutputObject
    >;

    "ValidatorRegistered(address,uint256)": TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
    ValidatorRegistered: TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;

    "VerdictSubmitted(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      VerdictSubmittedEvent.InputTuple,
      VerdictSubmittedEvent.OutputTuple,
      VerdictSubmittedEvent.OutputObject
    >;
    VerdictSubmitted: TypedContractEvent<
      VerdictSubmittedEvent.InputTuple,
      VerdictSubmittedEvent.OutputTuple,
      VerdictSubmittedEvent.OutputObject
    >;
  };
}
