/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ReputationRegistry {
  export type VerdictRecordStruct = {
    disputeId: BigNumberish;
    agent: AddressLike;
    outcome: BigNumberish;
    timestamp: BigNumberish;
    reasoning: string;
  };

  export type VerdictRecordStructOutput = [
    disputeId: bigint,
    agent: string,
    outcome: bigint,
    timestamp: bigint,
    reasoning: string
  ] & {
    disputeId: bigint;
    agent: string;
    outcome: bigint;
    timestamp: bigint;
    reasoning: string;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentVerdicts"
      | "agents"
      | "baseReputation"
      | "bountyHunterThreshold"
      | "corToken"
      | "deactivateAgent"
      | "eliteJudgeThreshold"
      | "failureWeight"
      | "getAccuracy"
      | "getAgentRecord"
      | "getAgentVerdicts"
      | "getRegisteredAgents"
      | "hasBadge"
      | "isAgentActive"
      | "justiceContract"
      | "owner"
      | "reactivateAgent"
      | "recordVerdict"
      | "registerAgent"
      | "registerAgentViaJustice"
      | "registeredAgents"
      | "revokeBadge"
      | "setJusticeContract"
      | "successWeight"
      | "trustedMinerThreshold"
      | "updateBadgeThresholds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "BadgeAwarded"
      | "BadgeRevoked"
      | "ReputationUpdated"
      | "VerdictRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentVerdicts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "baseReputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bountyHunterThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "corToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eliteJudgeThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "failureWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccuracy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentVerdicts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBadge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "justiceContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVerdict",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgentViaJustice",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBadge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setJusticeContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "successWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedMinerThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateBadgeThresholds",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentVerdicts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyHunterThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "corToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eliteJudgeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failureWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccuracy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentVerdicts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "justiceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgentViaJustice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setJusticeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "successWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedMinerThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBadgeThresholds",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agent: AddressLike, reason: string];
  export type OutputTuple = [agent: string, reason: string];
  export interface OutputObject {
    agent: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    agentType: BigNumberish,
    metadata: string
  ];
  export type OutputTuple = [
    agent: string,
    agentType: bigint,
    metadata: string
  ];
  export interface OutputObject {
    agent: string;
    agentType: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BadgeAwardedEvent {
  export type InputTuple = [agent: AddressLike, badge: BigNumberish];
  export type OutputTuple = [agent: string, badge: bigint];
  export interface OutputObject {
    agent: string;
    badge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BadgeRevokedEvent {
  export type InputTuple = [agent: AddressLike, badge: BigNumberish];
  export type OutputTuple = [agent: string, badge: bigint];
  export interface OutputObject {
    agent: string;
    badge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    newScore: BigNumberish,
    successCount: BigNumberish,
    failureCount: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    newScore: bigint,
    successCount: bigint,
    failureCount: bigint
  ];
  export interface OutputObject {
    agent: string;
    newScore: bigint;
    successCount: bigint;
    failureCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictRecordedEvent {
  export type InputTuple = [
    agent: AddressLike,
    disputeId: BigNumberish,
    outcome: BigNumberish
  ];
  export type OutputTuple = [agent: string, disputeId: bigint, outcome: bigint];
  export interface OutputObject {
    agent: string;
    disputeId: bigint;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentVerdicts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        disputeId: bigint;
        agent: string;
        outcome: bigint;
        timestamp: bigint;
        reasoning: string;
      }
    ],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        agent: string;
        agentType: bigint;
        agentMetadata: string;
        createdAt: bigint;
        successCount: bigint;
        failureCount: bigint;
        totalVerdicts: bigint;
        reputationScore: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  baseReputation: TypedContractMethod<[], [bigint], "view">;

  bountyHunterThreshold: TypedContractMethod<[], [bigint], "view">;

  corToken: TypedContractMethod<[], [string], "view">;

  deactivateAgent: TypedContractMethod<
    [_agent: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  eliteJudgeThreshold: TypedContractMethod<[], [bigint], "view">;

  failureWeight: TypedContractMethod<[], [bigint], "view">;

  getAccuracy: TypedContractMethod<[_agent: AddressLike], [bigint], "view">;

  getAgentRecord: TypedContractMethod<
    [_agent: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        agent: string;
        agentType: bigint;
        successCount: bigint;
        failureCount: bigint;
        totalVerdicts: bigint;
        reputationScore: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getAgentVerdicts: TypedContractMethod<
    [_agent: AddressLike],
    [ReputationRegistry.VerdictRecordStructOutput[]],
    "view"
  >;

  getRegisteredAgents: TypedContractMethod<[], [string[]], "view">;

  hasBadge: TypedContractMethod<
    [_agent: AddressLike, _badge: BigNumberish],
    [boolean],
    "view"
  >;

  isAgentActive: TypedContractMethod<[_agent: AddressLike], [boolean], "view">;

  justiceContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateAgent: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  recordVerdict: TypedContractMethod<
    [
      _agent: AddressLike,
      _disputeId: BigNumberish,
      _outcome: BigNumberish,
      _reasoning: string
    ],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [_agentType: BigNumberish, _metadata: string],
    [string],
    "nonpayable"
  >;

  registerAgentViaJustice: TypedContractMethod<
    [_agent: AddressLike, _agentType: BigNumberish, _metadata: string],
    [void],
    "nonpayable"
  >;

  registeredAgents: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  revokeBadge: TypedContractMethod<
    [_agent: AddressLike, _badge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setJusticeContract: TypedContractMethod<
    [_justice: AddressLike],
    [void],
    "nonpayable"
  >;

  successWeight: TypedContractMethod<[], [bigint], "view">;

  trustedMinerThreshold: TypedContractMethod<[], [bigint], "view">;

  updateBadgeThresholds: TypedContractMethod<
    [
      _trustedMiner: BigNumberish,
      _eliteJudge: BigNumberish,
      _bountyHunter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentVerdicts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        disputeId: bigint;
        agent: string;
        outcome: bigint;
        timestamp: bigint;
        reasoning: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        agent: string;
        agentType: bigint;
        agentMetadata: string;
        createdAt: bigint;
        successCount: bigint;
        failureCount: bigint;
        totalVerdicts: bigint;
        reputationScore: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "baseReputation"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bountyHunterThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "corToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<
    [_agent: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eliteJudgeThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "failureWeight"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccuracy"
  ): TypedContractMethod<[_agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentRecord"
  ): TypedContractMethod<
    [_agent: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        agent: string;
        agentType: bigint;
        successCount: bigint;
        failureCount: bigint;
        totalVerdicts: bigint;
        reputationScore: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentVerdicts"
  ): TypedContractMethod<
    [_agent: AddressLike],
    [ReputationRegistry.VerdictRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasBadge"
  ): TypedContractMethod<
    [_agent: AddressLike, _badge: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgentActive"
  ): TypedContractMethod<[_agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "justiceContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordVerdict"
  ): TypedContractMethod<
    [
      _agent: AddressLike,
      _disputeId: BigNumberish,
      _outcome: BigNumberish,
      _reasoning: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [_agentType: BigNumberish, _metadata: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgentViaJustice"
  ): TypedContractMethod<
    [_agent: AddressLike, _agentType: BigNumberish, _metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredAgents"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "revokeBadge"
  ): TypedContractMethod<
    [_agent: AddressLike, _badge: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setJusticeContract"
  ): TypedContractMethod<[_justice: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "successWeight"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trustedMinerThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateBadgeThresholds"
  ): TypedContractMethod<
    [
      _trustedMiner: BigNumberish,
      _eliteJudge: BigNumberish,
      _bountyHunter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BadgeAwarded"
  ): TypedContractEvent<
    BadgeAwardedEvent.InputTuple,
    BadgeAwardedEvent.OutputTuple,
    BadgeAwardedEvent.OutputObject
  >;
  getEvent(
    key: "BadgeRevoked"
  ): TypedContractEvent<
    BadgeRevokedEvent.InputTuple,
    BadgeRevokedEvent.OutputTuple,
    BadgeRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictRecorded"
  ): TypedContractEvent<
    VerdictRecordedEvent.InputTuple,
    VerdictRecordedEvent.OutputTuple,
    VerdictRecordedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address,string)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,uint8,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "BadgeAwarded(address,uint8)": TypedContractEvent<
      BadgeAwardedEvent.InputTuple,
      BadgeAwardedEvent.OutputTuple,
      BadgeAwardedEvent.OutputObject
    >;
    BadgeAwarded: TypedContractEvent<
      BadgeAwardedEvent.InputTuple,
      BadgeAwardedEvent.OutputTuple,
      BadgeAwardedEvent.OutputObject
    >;

    "BadgeRevoked(address,uint8)": TypedContractEvent<
      BadgeRevokedEvent.InputTuple,
      BadgeRevokedEvent.OutputTuple,
      BadgeRevokedEvent.OutputObject
    >;
    BadgeRevoked: TypedContractEvent<
      BadgeRevokedEvent.InputTuple,
      BadgeRevokedEvent.OutputTuple,
      BadgeRevokedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "VerdictRecorded(address,uint256,uint8)": TypedContractEvent<
      VerdictRecordedEvent.InputTuple,
      VerdictRecordedEvent.OutputTuple,
      VerdictRecordedEvent.OutputObject
    >;
    VerdictRecorded: TypedContractEvent<
      VerdictRecordedEvent.InputTuple,
      VerdictRecordedEvent.OutputTuple,
      VerdictRecordedEvent.OutputObject
    >;
  };
}
