/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DeployJudgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "corTokenAddress"
      | "deploy"
      | "getDeployedAddresses"
      | "initialValidatorAddress"
      | "justiceAddress"
      | "reputationRegistryAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JusticeDeployed"
      | "ReputationRegistryDeployed"
      | "ValidatorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "corTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialValidatorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "justiceAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistryAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "corTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialValidatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "justiceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistryAddress",
    data: BytesLike
  ): Result;
}

export namespace JusticeDeployedEvent {
  export type InputTuple = [justice: AddressLike];
  export type OutputTuple = [justice: string];
  export interface OutputObject {
    justice: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationRegistryDeployedEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegisteredEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeployJudge extends BaseContract {
  connect(runner?: ContractRunner | null): DeployJudge;
  waitForDeployment(): Promise<this>;

  interface: DeployJudgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  corTokenAddress: TypedContractMethod<[], [string], "view">;

  deploy: TypedContractMethod<
    [_corTokenAddress: AddressLike, _initialValidatorAddress: AddressLike],
    [[string, string]],
    "nonpayable"
  >;

  getDeployedAddresses: TypedContractMethod<
    [],
    [
      [string, string, string] & {
        _justice: string;
        _reputationRegistry: string;
        _corToken: string;
      }
    ],
    "view"
  >;

  initialValidatorAddress: TypedContractMethod<[], [string], "view">;

  justiceAddress: TypedContractMethod<[], [string], "view">;

  reputationRegistryAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "corTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [_corTokenAddress: AddressLike, _initialValidatorAddress: AddressLike],
    [[string, string]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeployedAddresses"
  ): TypedContractMethod<
    [],
    [
      [string, string, string] & {
        _justice: string;
        _reputationRegistry: string;
        _corToken: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialValidatorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "justiceAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reputationRegistryAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "JusticeDeployed"
  ): TypedContractEvent<
    JusticeDeployedEvent.InputTuple,
    JusticeDeployedEvent.OutputTuple,
    JusticeDeployedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationRegistryDeployed"
  ): TypedContractEvent<
    ReputationRegistryDeployedEvent.InputTuple,
    ReputationRegistryDeployedEvent.OutputTuple,
    ReputationRegistryDeployedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistered"
  ): TypedContractEvent<
    ValidatorRegisteredEvent.InputTuple,
    ValidatorRegisteredEvent.OutputTuple,
    ValidatorRegisteredEvent.OutputObject
  >;

  filters: {
    "JusticeDeployed(address)": TypedContractEvent<
      JusticeDeployedEvent.InputTuple,
      JusticeDeployedEvent.OutputTuple,
      JusticeDeployedEvent.OutputObject
    >;
    JusticeDeployed: TypedContractEvent<
      JusticeDeployedEvent.InputTuple,
      JusticeDeployedEvent.OutputTuple,
      JusticeDeployedEvent.OutputObject
    >;

    "ReputationRegistryDeployed(address)": TypedContractEvent<
      ReputationRegistryDeployedEvent.InputTuple,
      ReputationRegistryDeployedEvent.OutputTuple,
      ReputationRegistryDeployedEvent.OutputObject
    >;
    ReputationRegistryDeployed: TypedContractEvent<
      ReputationRegistryDeployedEvent.InputTuple,
      ReputationRegistryDeployedEvent.OutputTuple,
      ReputationRegistryDeployedEvent.OutputObject
    >;

    "ValidatorRegistered(address)": TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
    ValidatorRegistered: TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
  };
}
